#!/bin/sh -e

set -o pipefail

hsfiles=`find "$@" -name '*.hs' -or -name '*.lhs'`
unformattedFiles=

for hsfile in $hsfiles
do
        # use `diff` instead of `ormolu check` because ormolu does exit 0 any case
	if ! ormolu $hsfile | diff $hsfile -
	then
		unformattedFiles="$unformattedFiles $hsfile"
	fi
done

[ -z "$unformattedFiles" ] && exit 0

echo "please format these files:"
for file in $unformattedFiles
do
	echo $file
done

exit 1
