#!/bin/sh -e

format() {
	ormolu
}

hsfiles=`find "$@" -name '*.hs' -or -name '*.lhs'`
unformattedFiles=

for hsfile in $hsfiles
do
	if ! cat $hsfile | format | diff $hsfile -
	then
		unformattedFiles="$unformattedFiles $hsfile"
	fi
done

[ -z "$unformattedFiles" ] && exit 0

echo "please format these files:"
for file in $unformattedFiles
do
	echo $file
done

exit 1
