stages:
- build

variables:
  STACK_ROOT: "$CI_PROJECT_DIR/.cache/stack"

cache:
  key: "$CI_JOB_NAME"
  paths:
  - .cache

.stack: &stack_build
  stage: build
  script:
  - make all

stack-latest:
  <<: *stack_build
  image: fpco/stack-build-small:lts
  allow_failure: true
  script:
  - make STACK_ARGS='--resolver lts' all

stack-14.6:
  <<: *stack_build
  image: fpco/stack-build-small:lts-14.6
  variables:
    STACK_YAML: stack-lts-14.6.yaml

.cabal: &cabal_job
  stage: build
  before_script:
  - mkdir -p "$HOME/.cabal"
  - (test -d .cache/cabal && cp -r .cache/cabal/* "$HOME/.cabal") || true
  script:
  - cabal v2-update -f pedantic
  - cabal v2-build -f pedantic
  - cabal v2-test -f pedantic test
  - cabal v2-install --help
  - cabal v2-install -f pedantic --installdir build exe:hookmark
  - cabal v2-test -f pedantic regression
  after_script:
  - mkdir -p .cache/cabal
  - cp -r "$HOME/.cabal/"* .cache/cabal

cabal-latest:
  <<: *cabal_job
  image: haskell:latest
  allow_failure: true

cabal-8.8.1:
  <<: *cabal_job
  image: haskell:8.8.1

cabal-8.6.5:
  <<: *cabal_job
  image: haskell:8.6.5
  script:
  - cabal v2-update -f pedantic
  - cabal v2-build -f pedantic
  - cabal v2-test -f pedantic test
  - cabal v2-install -f pedantic --symlink-bindir build exe:hookmark
  - cabal v2-test -f pedantic regression
