stages:
- build

variables:
  STACK_ROOT: "$CI_PROJECT_DIR/.cache/stack"

cache:
  key: "$CI_JOB_NAME"
  paths:
  - .cache

linux-x86_64:
  stage: build
  image: neosimsim/ghc:8.8.2
  before_script:
  - mkdir -p "$HOME/.cabal"
  - (test -d .cache/cabal && cp -r .cache/cabal/* "$HOME/.cabal") || true
  - cabal v2-update
  - cabal configure --constraint 'cryptonite -integer-gmp' --constraint 'hashable -integer-gmp' --constraint 'scientific +integer-simple' --constraint 'integer-logarithms -integer-gmp'
  script:
  - make CABAL_BUILD_ARGS='-f static' all
  after_script:
  - mv build linux-x86_64
  - mkdir -p .cache/cabal
  - cp -r "$HOME/.cabal/"* .cache/cabal
  artifacts:
    name: "hookmark-$CI_COMMIT_SHORT_SHA-linux-x86_64"
    paths:
    - linux-x86_64/hookmark
    - linux-x86_64/hookmark-web
    expire_in: 1 week

.cabal: &cabal_job
  stage: build
  before_script:
  - mkdir -p "$HOME/.cabal"
  - (test -d .cache/cabal && cp -r .cache/cabal/* "$HOME/.cabal") || true
  - cabal v2-update
  script:
  - make all
  after_script:
  - mkdir -p .cache/cabal
  - cp -r "$HOME/.cabal/"* .cache/cabal

cabal-ghc-latest:
  <<: *cabal_job
  image: haskell:latest
  allow_failure: true

cabal-ghc-8.8.1:
  <<: *cabal_job
  image: haskell:8.8.1

cabal-ghc-8.6.5:
  <<: *cabal_job
  image: haskell:8.6.5
  script:
  - cabal v2-build -f pedantic
  - cabal v2-test -f pedantic test
  - cabal v2-install -f pedantic --symlink-bindir build exe:hookmark
  - cabal v2-test -f pedantic regression

check:
  <<: *cabal_job
  image: haskell:8.6.5
  script:
  - mkdir -p tools
  # haskell:8.6.5 comes with cabal-2.4.1.0, therefore we cannot use `make tools`
  - (cd tools && cabal v2-install --symlink-bindir . --constraint 'haskell-src-exts < 1.22' hfmt-0.2.3.1)
  - (cd tools && cabal v2-install --symlink-bindir . cabal-fmt-0.1.2)
  - make check
