#!/bin/sh
# pseudo git command to which just prints the argument
# can be used to check, if git gets invoked.

log() {
	if [ -n "$GITLOG" ]
	then
		tee -a "$GITLOG"
	else
		cat
	fi
}

echo "execute git with $@" | log
